#!/usr/bin/env ruby

require 'arxutils'
require 'feedlrop'

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

token = ARGV[0]
hs = {
  "db_dir" => Arxutils::Dbutil::DB_DIR,
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => Arxutils::Dbutil::CONFIG_DIR,
  "dbconfig" => dbconfig,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}

fo = Feedlrop::Feedlrop.new(
                            token ,
                            :db,
                            hs
                            )
#fo.get_all_unread_count
fo.print_user_profile
fo.print_subscription


