#!/usr/bin/env ruby

require 'arxutils'
require 'feedlrop'

#dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

token = ARGV[0]
env = ENV['ENV']
#env ||= "development"
env ||= "production"

hs = {
  "db_dir" => Arxutils::Dbutil::DB_DIR,
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => Arxutils::Dbutil::CONFIG_DIR,
  "dbconfig" => dbconfig,
  "env" => env,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}

opts = { }

fo = Feedlrop::Feedlrop.new(
                            token ,
                            :db,
                            hs,
                            opts,
                            )
fo.csv_open
fo.get_all_unread_count
fo.csv_close

