#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require 'feedlrop'

data_ary = [
  {
    :flist => %W!noitem!,
    :classname => "Countdatetime",
    :classname_downcase => "countdatetime",
    :items => [
              ["countdatetime" , "datetime", "false"],
            ],
    :plural => "countdatetimes"
  },

  {
    :flist => %W!base!,
    :classname => "Unreadfeed",
    :classname_downcase => "unreadfeed",

    :items => [
              ["time_id" , "integer", "false"],
              ["category" , "string", "false"],
              ["url" , "string", "false"],
              ["unread_count" , "integer", "false"],
             ],
    :plural => "unreadfeeds"
  },
]

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

forced = true
Arxutils::Migrate.migrate(
                          data_ary,
                          0,
                          dbconfig,
                          forced
                          )
