#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'dbinit'
require 'migrate'
require 'feedlrop'

data_ary = [
  {
    :flist => %W!noitem!,
    :classname => "Countdatetime",
    :classname_downcase => "countdatetime",
    :items => [
              ["countdatetime" , "datetime", "false"],
            ],
    :plural => "countdatetimes"
  },

  {
    :flist => %W!base!,
    :classname => "Unreadfeed",
    :classname_downcase => "unreadfeed",

    :items => [
              ["time_id" , "integer", "false"],
              ["category" , "string", "false"],
              ["url" , "string", "false"],
              ["unread_count" , "integer", "false"],
             ],
    :plural => "unreadfeeds"
  },
]

forced = true
mig = Arxutils::Migrate.new(Arxutils::DB_DIR, Arxutils::MIGRATE_DIR  , Arxutils::CONFIG_DIR , Arxutils::DBCONFIG, Arxutils::DATABASELOG , forced )
data_ary.reduce(0) do |next_num , x| 
  mig.make( next_num , x )
end
mig.migrate
